name: Build Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build Release APK
      run: gradle assembleRelease

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      # Этот шаг пропустится, если секреты не настроены, и будет использована тестовая подпись

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v6
      with:
        name: WindYM-Release
        path: ${{steps.sign_app.outputs.signedReleaseFile || 'app/build/outputs/apk/release/*.apk'}}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        tag_name: latest
        name: Последняя сборка (Latest)
        body: Автоматическая сборка приложения WindYM
        files: ${{steps.sign_app.outputs.signedReleaseFile || 'app/build/outputs/apk/release/*.apk'}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
